simulation:
  prim_file: /Volumes/RESEARCHUSB/URAP/Outputs/9_omega/out/
  uov_file: /Volumes/RESEARCHUSB/URAP/Outputs/9_omega/out/
  output_path: /Volumes/RESEARCHUSB/URAP/Analysis/profile_plotter_2d/out/
  outer_boundary: 2e7
  density: 1
  vr_range: [0, 10]
  vphi_range: [-0.25, 0.25]
  tol: 1e-15
  title: null
  smooth_surfaces: false

prop:
  M: 2.7839e33 
  R: 1.2e6 
  B: 3e15
  Omega: 20.9439510239
  rho: 4e11

eos:
  type: isothermal
  cT: 3e9
  calculate_iso_quantities: true

animation:
  create: false
  extension: png
  find: false
  animation_name: animation.mp4
  